#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore 
#gamescope &

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# auto start
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
~/.config/polybar/launch-bars.sh &
nitrogen --restore & 
dunst &

feh --bg-scale --randomize ~/Pictures/wallpapers/*
