[global/wm]
margin-bottom = 0
margin-top = 0
include-file = ~/.config/polybar/themes/macchiato.ini
include-file = ~/.config/polybar/modules.ini

; full
[bar/eDP-1-Full]
wm-restack = bspwm
bottom = false
monitor = eDP-1
emable-ipc = true
fixed-center = true
width = 99%
height = 40
offset-x = 12
offset-y = 10
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
line-color = ${colors.blue}
border-bottom-size = 0
border-bottom-color = ${colors.blue}
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
;font-0 = "Comfortaa Medium:size=12;3"
font-0 = "iosevka:size=12;3"
font-1 = "Material Design Icons Desktop pixelsize=20;5"
modules-left = bspwm title
modules-center = info-cava
modules-right = updates alsa backlight battery date network 
tray-position = right
tray-detached = false
tray-maxsize = 20
tray-background = ${colors.base}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 4
tray-scale = 1.0

[bar/eDP-1-Left]
wm-restack = bspwm
bottom = false
monitor = eDP-1
emable-ipc = true
fixed-center = true
width = 21.125%
height = 30
offset-x = 12
offset-y = 10
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
line-color = ${colors.blue}
border-bottom-size = 0
border-bottom-color = ${colors.blue}
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
;font-0 = "Comfortaa Medium:size=12;3"
font-0 = "iosevka:size=12;3"
font-1 = "Material Design Icons Desktop pixelsize=20;5"
modules-left = 
modules-center = bspwm
modules-right =  

[bar/eDP-1-Left-Short]
wm-restack = bspwm
bottom = false
monitor = eDP-1
emable-ipc = true
fixed-center = true
width = 10.5625%
height = 30
offset-x = 12
offset-y = 10
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
line-color = ${colors.blue}
border-bottom-size = 0
border-bottom-color = ${colors.blue}
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
;font-0 = "Comfortaa Medium:size=12;3"
font-0 = "iosevka:size=12;3"
font-1 = "Material Design Icons Desktop pixelsize=20;5"
modules-left = 
modules-center = bspwm
modules-right =  

[bar/eDP-1-Center]
wm-restack = bspwm
bottom = false
monitor = eDP-1
emable-ipc = true
fixed-center = true
width = 10%
height = 30
offset-x = 45%
offset-y = 10
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
line-color = ${colors.blue}
border-bottom-size = 0
border-bottom-color = ${colors.blue}
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
;font-0 = "Comfortaa Medium:size=12;3"
font-0 = "iosevka:size=12;3"
font-1 = "Symbols Nerd Font:style=regular;pixelsize=9; 3"
font-2 = FontAwesome:style=Regular:pixelsize=9; 2
font-3 = Font Awesome 6 Brands:pixelsize=9; 2
modules-left = 
modules-center = ip
modules-right =  

[bar/eDP-1-Right]
wm-restack = bspwm
bottom = false
monitor = eDP-1
emable-ipc = true
fixed-center = true
width = 28%
height = 30
offset-x = 71.375%
offset-y = 10
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
line-color = ${colors.blue}
border-bottom-size = 0
border-bottom-color = ${colors.blue}
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
;font-0 = "Comfortaa Medium:size=12;3"
font-0 = "iosevka:size=12;3"
font-1 = "Material Design Icons Desktop pixelsize=20;5"
modules-left = 
modules-center = alsa backlight battery date network  
modules-right =

[bar/Bottom-Left]
wm-restack = bspwm
bottom = true
monitor = ${env:MONITOR:}
emable-ipc = true
fixed-center = true
width = 20%
height = 30
offset-x = 12
offset-y = 10
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
line-color = ${colors.blue}
border-bottom-size = 0
border-bottom-color = ${colors.blue}
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
;font-0 = "Comfortaa Medium:size=12;3"
font-0 = "iosevka:size=12;3"
font-1 = "Material Design Icons Desktop pixelsize=20;5"
modules-left = 
modules-center = memory cpu temperature filesystem  
modules-right =

[bar/Bottom-Center]
wm-restack = bspwm
bottom = true
monitor = ${env:MONITOR:}
emable-ipc = true
fixed-center = true
width = 6%
;width = 20%
height = 30
offset-x = 47%
offset-y = 10
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
line-color = ${colors.blue}
border-bottom-size = 0
border-bottom-color = ${colors.blue}
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
;font-0 = "Comfortaa Medium:size=12;3"
font-0 = "iosevka:size=12;3"
font-1 = "Material Design Icons Desktop pixelsize=20;5"
modules-left = 
modules-center = info-cava  
modules-right =  



[bar/Bottom-Right]
wm-restack = bspwm
bottom = true
monitor = ${env:MONITOR:}
emable-ipc = true
fixed-center = true
width = 7%
height = 30
offset-x = 92.625%
offset-y = 10
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
line-color = ${colors.blue}
border-bottom-size = 0
border-bottom-color = ${colors.blue}
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
;font-0 = "Comfortaa Medium:size=12;3"
font-0 = "iosevka:size=12;3"
font-2 = font-2 = Weather Icons:size=12;1
modules-left = 
modules-center = info-hackspeed 
modules-right =



[bar/HDMI-A-0]
wm-restack = bspwm
bottom = false
monitor = HDMI-A-0
fixed-center = true
width = 100%
height = 40
offset-x = 0%
offset-y = 0
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
line-color = ${colors.blue}
border-bottom-size = 0
border-bottom-color = ${colors.blue}
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
font-0 = "iosevka:size=12;3"
font-1 = "Material Design Icons Desktop pixelsize=20;5"
font-2 = "Symbols Nerd Font:style=regular;pixelsize=9; 3"
modules-left = bspwm
modules-center = ip
modules-right = alsa backlight battery date network 
;tray-position = right
;tray-detached = false
;tray-maxsize = 20
;tray-background = ${colors.base}
;tray-offset-x = 0
;tray-offset-y = 0
;tray-padding = 4
;tray-scale = 1.0
